services:
  db:
    build:
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  node-service:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: mydb
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_ROOT_PASSWORD: rootpassword
    deploy:
      replicas: 3 
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-service
        
volumes:
  db-data:

# docker-compose ps
# docker-compose logs nginx

# docker-compose down
# docker-compose up --build -d
# docker-compose up -d